version: "3.7"

networks:
  crwler:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/defaults.conf:/etc/nginx/conf.d/defaults.conf
    depends_on:
      - php
      - mysql
    networks:
      - crwler
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crwler
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - crwler
  phpmyadmin:
      depends_on:
        - mysql
      image: phpmyadmin/phpmyadmin
      restart: always
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: secret
      ports:
        - 8083:80
      networks:
        - crwler
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./app:/var/www/html
    environment:
      - upload_max_filesize=60M
      - post_max_size=60M  
    ports:
      - "10000:10000"
    networks:
      - crwler
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - crwler
  npm:
    image: node:16-alpine3.11
    container_name: npm
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      crwler:
